version: '3'
services:
  backend:
    image: openjdk:11-jdk-slim
    volumes:
      - ./backend/target/backend.jar:/app.jar
    command: "java -jar /app.jar"
    depends_on:
      - postgres
  postgres:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: secret
    volumes:
      - ./keycloak.json:/tmp/keycloak.json
    depends_on:
      - postgres
    command: "-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/keycloak.json"
  frontend:
    build: ./frontend/docker/
    volumes:
    - ./frontend:/app
  nginx:
    image: nginx
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/site.conf
    ports:
     - "8080:8080"
    depends_on:
      - backend
      - keycloak
      - frontend
