server:
  servlet:
    context-path: "/api"

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://keycloak:8080/auth/realms/exam/protocol/openid-connect/certs"

flyway:
  url: jdbc:postgresql://postgres:5432/postgres
  username: postgres
  password: postgres

springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger/ui"
  api-docs:
    enabled: true
    path: "/swagger/docs"

management:
  endpoints:
    web:
      exposure:
        include: "*"
