spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:9080/auth/realms/exam/protocol/openid-connect/certs"
server:
  servlet:
    context-path: "/api"
