FROM node:latest as builder
COPY src/main/angular/package.json ./
COPY src/main/angular/package-lock.json ./
RUN npm ci && mkdir /ng-app && mv ./node_modules ./ng-app
WORKDIR /ng-app
COPY src/main/angular .
RUN npm run ng build -- --prod --output-path=dist

FROM nginx
COPY src/main/docker/nginx.conf /etc/nginx/conf.d/
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /ng-app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
