version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data2
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  keycloak:
    image: jboss/keycloak
    ports:
      - "9080:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: secret
      KEYCLOAK_IMPORT: /tmp/exam-realm.json
      KEYCLOAK_LOGLEVEL: INFO
      PROXY_ADDRESS_FORWARDING: "true"
    volumes:
      - ./keycloak.json:/tmp/exam-realm.json 
    depends_on:
      - postgres
