CREATE TABLE SOLUTION_ATTEMPT (ID UUID PRIMARY KEY, EXAM_ID UUID, SUCCESS BOOLEAN, TIME TIMESTAMP, USER_ID VARCHAR(255), FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255), COMMENT TEXT);
CREATE TABLE QUESTION (ID UUID PRIMARY KEY, TEXT TEXT, CORRECT_OPTION INTEGER, EXAM_ID UUID);
CREATE TABLE EXAM_QUESTIONS (EXAM_ID UUID, QUESTIONS_ID UUID);
CREATE TABLE QUESTION_OPTIONS (QUESTION_ID UUID, OPTIONS TEXT);
CREATE TABLE EXAM (ID UUID, OPTION TEXT, OWNER VARCHAR(255), TITLE VARCHAR(255), TEXT TEXT, MAX_ATTEMPTS INTEGER, CLOSED BOOLEAN);