CREATE TABLE PARTICIPATION (
    ID UUID PRIMARY KEY,
    EXAM_ID UUID,
    SUCCESSFUL BOOLEAN,
    TIME TIMESTAMP,
    USER_ID VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    REMAINING_ATTEMPTS INTEGER,
    COMMENT TEXT);

CREATE VIEW LATEST_PARTICIPATION_VIEW AS SELECT
    p1.ID as ID,
    p1.EXAM_ID as EXAM_ID,
    p1.SUCCESSFUL as SUCCESSFUL,
    p1.TIME as TIME,
    p1.USER_ID as USER_ID,
    p1.FIRST_NAME as FIRST_NAME,
    p1.LAST_NAME as LAST_NAME,
    p1.REMAINING_ATTEMPTS as REMAINING_ATTEMPTS,
    p1.COMMENT as COMMENT
FROM PARTICIPATION p1
INNER JOIN (
    SELECT EXAM_ID, USER_ID, max(TIME) AS TIME
    FROM PARTICIPATION
    GROUP BY EXAM_ID, USER_ID
) p2 ON
    p1.EXAM_ID = p2.EXAM_ID AND
    p1.USER_ID = p2.USER_ID AND
    p1.TIME = p2.TIME;

CREATE TABLE QUESTION (
    ID UUID PRIMARY KEY,
    TEXT TEXT,
    CORRECT_OPTION INTEGER,
    EXAM_ID UUID);

CREATE TABLE EXAM_QUESTIONS (
    EXAM_ID UUID,
    QUESTIONS_ID UUID);

CREATE TABLE QUESTION_OPTIONS (
    QUESTION_ID UUID,
    OPTIONS TEXT);

CREATE TABLE EXAM (
    ID UUID,
    OPTION TEXT,
    OWNER VARCHAR(255),
    TITLE VARCHAR(255),
    TEXT TEXT,
    MAX_ATTEMPTS INTEGER,
    CLOSED BOOLEAN);